apiVersion: v1
kind: Service
metadata:
  name: gvc
  namespace: grras
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: grras
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
       - name: dbvol1
         hostPath:
            path: "/data"
            type: Directory
      containers:
      - image: nginx:1.14.2
        name: nginx
        volumeMounts:
           - name: dbvol1
             mountPath: /usr/share/nginx/html/
